#!/bin/sh

# Source each installed module that has git hooks
# shellcheck disable=SC2013
for module in $(cat "$DOTFILES/.selected"); do
	file="$DOTFILES/modules/$module/git/hooks/post-commit"
	if [ -f "$file" ]; then
		# shellcheck disable=SC1090
		. "$file"
	fi
done

command -v git-lfs >/dev/null 2>&1 || {
	printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'post-commit' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."
	exit 2
}
git lfs post-commit "$@"
